### ISSUE TITLE
Step 4 test does not fail as described

### ISSUE THREAD

**Issue by fdansey-ostmodern** [pact-foundation/pact-workshop-js#109]
### Summary
The instructions in step 4 read:

> _"validate the pact generated by the consumer is valid, by executing it against the running service provider, which should fail"_

Also: what is meant by, _"the running service provider"_?

Instead, the test passes with output different from the README file.

### Steps to reproduce
1. Checkout branch, `step4`.
2. Run the test, ```npm run test:pact --prefix provider```

The test script is https://github.com/pact-foundation/pact-workshop-js/blob/step4/provider/product/product.pact.test.js
The documentation at https://github.com/pact-foundation/pact-workshop-js/blob/step4/README.md#step-4---verify-the-provider says that the test should fail, but it succeeds with the output:
```
$ npm run test:pact --prefix provider

> product-service@1.0.0 test:pact
> npx jest --testTimeout=30000 --testMatch "**/*.pact.test.js"


 RUNS  product/product.pact.test.js
2023-04-19T12:35:17.633449Z  WARN ThreadId(21) pact_matching::metrics: 

Please note:
We are tracking events anonymously to gather important usage statistics like Pact version and operating system. To disable tracking, set the 'PACT_DO_NOT_TRACK' environment variable to 'true'.

[2023-04-19 12:35:17.626 +0000] INFO (27052 on blarn): pact@10.1.1: Verifying provider
[2023-04-19 12:35:17.630 +0000] INFO (27052 on blarn): pact-core@13.7.8: Verifying Pacts.
[2023-04-19 12:35:17.630 +0000] INFO (27052 on blarn): pact-core@13.7.8: Verifying Pact Files
 PASS  product/product.pact.test.js
  Pact Verification
    ✓ validates the expectations of ProductService (111ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.828s, estimated 1s
Ran all test suites.
[2023-04-19 12:35:17.729 +0000] INFO (27052 on blarn): pact-core@13.7.8: Verification successful
  console.log product/product.pact.test.js:22
    finished: 0
```

**Comment by fdansey-ostmodern** [comment]
I think the problem is that:
1. the documentation says that
> _"A pact file should have been generated in consumer/pacts/frontendwebsite-productservice.json"_

Whereas, I found the file name created was actually, `consumer/pacts/FrontendWebsite-ProductService.json`

2. The product pact test function (`Verifier(opts).verifyProvider()`) **does not fail** when the path defined in `pactUrls` does not point to a readable file.

**Comment by YOU54F** [comment]
Updated now across all steps and readmes
