### ISSUE TITLE
Step 1 + 2 Don't see any error message on the products page

### ISSUE THREAD

**Issue by orassyag** [pact-foundation/pact-workshop-js#110]
Everything runs as expected, but you don't see any error messages on the screen:

<img width="1077" alt="image" src="https://github.com/pact-foundation/pact-workshop-js/assets/138584701/090bb010-548f-46c6-b831-cb032c596a01">

**Comment by YOU54F** [comment]
Now fixed, the ErrorBoundary.js now reads from the history state, which is set on failure from the api call

https://github.com/pact-foundation/pact-workshop-js/blob/61c2b7866b2f24471c5a7433ab9165bcc3a48b6d/consumer/src/ErrorBoundary.js#L34
https://github.com/pact-foundation/pact-workshop-js/blob/61c2b7866b2f24471c5a7433ab9165bcc3a48b6d/consumer/src/App.js#L84

**Comment by orassyag** [comment]
Thanks
