### ISSUE TITLE
pact publishing error can_i_deploy_long_desc.txt

### ISSUE THREAD

**Issue by masadaark** [pact-foundation/pact-workshop-js#149]
pact-workshop-js/consumer/node_modules/@pact-foundation/pact-core/standalone/windows-x64-2.0.3/pact/lib/vendor/ruby/3.2.0/gems/pact_broker-client-1.68.0/lib/pact_broker/client/cli/can_i_deploy_long_desc.txt

this [link](https://stackoverflow.com/questions/79045237/pact-file-publishing-error-can-i-deploy-long-desc-txt-not-found-in-pact-worksho)

**Comment by mefellows** [comment]
I think your issue might be related to https://github.com/pact-foundation/pact-js-core/issues/101 or https://github.com/pact-foundation/pact-js/issues/670. 

I thought this might have been fixed with the 2.x.x Ruby binaries, but seems like it may not have. 

You could try moving closer to `c:` root path, or the registry fixes identified in the linked issues.

**Comment by masadaark** [comment]
how can i fix 2.x.x ruby binaries , i follow to pact-workshop-js https://github.com/pact-foundation/pact-workshop-js
with js i never download ruby on my local machine

**Comment by masadaark** [comment]
> I think your issue might be related to [pact-foundation/pact-js-core#101](https://github.com/pact-foundation/pact-js-core/issues/101) or [pact-foundation/pact-js#670](https://github.com/pact-foundation/pact-js/issues/670).
> 
> I thought this might have been fixed with the 2.x.x Ruby binaries, but seems like it may not have.
> 
> You could try moving closer to `c:` root path, or the registry fixes identified in the linked issues.

how can i fix 2.x.x ruby binaries , i follow to pact-workshop-js https://github.com/pact-foundation/pact-workshop-js
with js i never download ruby on my local machine

**Comment by mefellows** [comment]
We package some Ruby CLIs as part of Pact JS, these are the files causing the issue above. They are already on the 2.x.x (note the `2.0.3` in your error above). Try the suggestion of moving closer to `c:`.

**Comment by mefellows** [comment]
If you have WSL, you could also try running the workshop on that.

**Comment by YOU54F** [comment]
pretty sure you will need to enable long paths in the registry as per the pact-js-cli readme. (i'll update the deps in the repo to use the new cli)

https://github.com/pact-foundation/pact-js-cli?tab=readme-ov-file#enable-long-paths

longer read.

there are two mechanisms, one set in the manifest of an exe, which is already set by rubyinstaller

https://github.com/oneclick/rubyinstaller2/blob/704d7a4810d6a40fe99d1373e1dd9cae17d08f08/recipes/sandbox/60-side-by-side-assembly.rake#L41

and the 2nd which is the registry value

you can see it being set in ruby installers CI system 

https://github.com/oneclick/rubyinstaller2/blob/704d7a4810d6a40fe99d1373e1dd9cae17d08f08/.github/workflows/ci.yml#L103-L106
