### ISSUE TITLE
step 11 - npx pact-broker package is not available, ideally replace with docker cli version of can-i-deploy

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-workshop-js#24]
yo dudes/dudettes, in the pact-workshop-js guide, it mentions an npx package called pact-broker which doesn’t exist

https://github.com/pact-foundation/pact-workshop-js#can-i-deploy
Should it point to the docker image of the ruby cli here?

https://github.com/pact-foundation/pact-ruby-cli#can-i-deploy

the image is here

https://hub.docker.com/r/pactfoundation/pact-cli

two ways we can run it via docker from the CLI

Attached to our host network

```
docker run --rm \
  --network='host' \
  pactfoundation/pact-cli:latest \
  broker can-i-deploy \
  --pacticipant FrontendWebsite \
               --broker-base-url http://localhost:8000 \
               --broker-username pact_workshop \
               --broker-password pact_workshop \
               --latest
```

Attached to our the default network started by the docker-compose setup

```
docker run --rm \
  --network='pact-workshop-js_default' \
  pactfoundation/pact-cli:latest \
  broker can-i-deploy \
  --pacticipant FrontendWebsite \
               --broker-base-url http://broker_app:80 \
               --broker-username pact_workshop \
               --broker-password pact_workshop \
               --latest
```

**Comment by mefellows** [comment]
`npx` just tries to find a binary with the same name in the tree. If you did a `find . -name pact-broker` there should be a file there.

e.g.

![Screen Shot 2021-04-09 at 11 44 20 am](https://user-images.githubusercontent.com/53900/114116926-ed112f00-9928-11eb-81b6-0b855e6e46d8.png)

is it not worknig for you?

**Comment by YOU54F** [comment]
this works `➜  pact-workshop-js git:(master) cd consumer && npx pact-broker` but the guide shows running everything from outside the provider/consumer folder

Closing now :)
