### ISSUE TITLE
issue running npm i on M1 Mac

### ISSUE THREAD

**Issue by country-bumpkin-software** [pact-foundation/pact-workshop-js#60]
If you clone the pact-workshop-js repo and try to install using a Mac m1 computer then you get the following error:

npm ERR! code EBADPLATFORM
[0] npm ERR! notsup Unsupported platform for @pact-foundation/pact-node@10.10.1: wanted {"os":"darwin,linux,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
[0] npm ERR! notsup Valid OS:    darwin,linux,win32
[0] npm ERR! notsup Valid Arch:  x64,ia32
[0] npm ERR! notsup Actual OS:   darwin
[0] npm ERR! notsup Actual Arch: arm64

**Comment by mefellows** [comment]
Please see https://github.com/pact-foundation/pact-js-core/issues/264. 

TL;DR - I think running in Rosetta mode will address it. You could also try upgrading to the latest Pact JS in the workshop code, to see if the temporary fix identified in the issue above does resolve it.

In the [next major release](https://github.com/pact-foundation/pact-js/#pact-js-v3) of Pact (, we'll have full first class support for M1, but that is probably a few months away.

**Comment by tomdickman** [comment]
I can confirm I got this running on Node 14.19.0 after following the instructions [here](https://apple.stackexchange.com/questions/409746/run-everything-in-rosetta-2-on-silicon-mac) to run my iTerm through Rosetta on my M1
