### ISSUE TITLE
Mismatch between instructions and sample code

### ISSUE THREAD

**Issue by sebrose** [pact-foundation/pact-workshop-js#62]
The instructions say the Pact file should be copied from `consumer/pacts` to `provider/pacts`...
BUT
`product.pact.test.js` looks for the Pact file in `consumer/pacts`.

I'm happy to fix, but which was intended?

(Personally I favour copying the Pact file & modifying `product.pact.test.js` to look in `provider/pacts`)

**Comment by mefellows** [comment]
Ah thanks, I thought I'd fixed all of those discrepancies.

When run as a larger group based workshop, I found that it was a common pain point having to copy the file each time, so we went with relative path.

Perhaps there's a better solution as it may have the unintended consequence of assuming this is good practice (despite step 11 addressing this).

**Comment by YOU54F** [comment]
>When run as a larger group based workshop, I found that it was a common pain point having to copy the file each time, so we went with relative path.

This is the main point, we want all the steps to run out the box, so a user can see the concepts with the idea of here is a step we baked earlier.

We could actually use a PACT_URL variable which could be a file, or a url which gets the user into the idea of verifying a single pact, (when the consumer changes) vs verifiying multiple pacts (when the provider changes)
