### ISSUE TITLE
npm ci fails with latest commit

### ISSUE THREAD

**Issue by gdsandrewmccafferty** [pact-foundation/pact-workshop-js#84]
I was using this repo some time around the 20th July (before commits on 27th), and didn't have any issues. 
I'm using node version `v14.18.2`, but my colleague had the same issues with the most recent version of node.
Bit confusing for newbies trying to get going with Pact! I was helping my colleague, and couldn't see what the difference was with her setup until I pulled the latest version.

Some time after the 20th July, commits have been added that cause this error on `npm ci`

```
[1] npm ERR! uglify-js not accessible from handlebars
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/andrewmccafferty/.npm/_cacache/_logs/2022-08-19T08_48_53_862Z-debug.log
[1] npm ci --prefix provider exited with code 1
[0] npm ERR! @types/node not accessible from @types/needle
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /Users/andrewmccafferty/.npm/_cacache/_logs/2022-08-19T08_49_05_730Z-debug.log
[0] npm ci --prefix consumer exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pact-workshop-js@0.1.0 postinstall: `concurrently "npm ci --prefix consumer" "npm ci --prefix provider"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pact-workshop-js@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrewmccafferty/.npm/_logs/2022-08-19T08_49_05_804Z-debug.log
```
When I then do the first step in the tutorial, namely `npm start --prefix consumer `, it fails because the first step didn't install any packages in the consumer or provider folders.

```
> consumer@0.1.0 start /Users/andrewmccafferty/Documents/git/bench/pact-workshop-js/consumer
> react-scripts start

sh: react-scripts: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! consumer@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the consumer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by mefellows** [comment]
Thanks for the report. It looks like maybe the pinned deps are incorrect. If you were open to having a stab at removing the lock files and trying again that would be great.

Otherwise I'll aim to look next week sometime.

**Comment by mefellows** [comment]
OK had a minute this afternoon and had a look. I'm not sure what was going on, but I took the liberty of updating to the latest Pact JS version whilst I was there.

Could you please give it a go?

**Comment by YOU54F** [comment]
Should be sorted across all steps now, thanks for raising

```
node --version
Now using node v18.17.1 (npm v9.6.7)
```
