### ISSUE TITLE
pact-broker publish not responding.

### ISSUE THREAD

**Issue by rikumolugds** [pact-foundation/pact-workshop-js#85]
I'm currently working through the workshop and on step 11, I seem to be unable to publish the consumer pact successfully. `    "pact:publish": "pact-broker publish ./pacts  --auto-detect-version-properties --broker-base-url=http://localhost:8000 --broker-username pact_workshop --broker-password pact_workshop "` just seems to hang indefinitely. It neither errors, times out, nor  does it  display the confirmation message. 
I am able to navigate to the broker on a browser and connect using curl after running `docker-compose up`. I have had the same tried on a colleague's machine and confirms the same issue happens. Working off HEAD on step11 branch.

**Comment by mefellows** [comment]
Try adding `--verbose` to the command see what happens. Does this happen on a work machine or a personal one?

**Comment by rikumolugds** [comment]
@mefellows thanks for your response. I have tried with --verbose option and it's the same issue. We are working off work machines.

**Comment by mefellows** [comment]
Sorry for the confusion, I was hoping the `--verbose` flag would provide some feedback on why it's not working. Are you able to please share the output when verbose is enabled?

**Comment by rikumolugds** [comment]
It still just hangs when I use that option, same as without. Is the script supposed to be logging somewhere? I don't see a logs folder generated.

**Comment by mefellows** [comment]
It should print to terminal. Do you have AV or anything installed?

What happens if you just run `pact-broker publish ./pacts --consumer-app-version="$(npx @pact-foundation/absolute-version)" --auto-detect-version-properties --broker-base-url=http://localhost:8000 --broker-username pact_workshop --broker-password pact_workshop` directly?

**Comment by rikumolugds** [comment]
I just tried that at it's the same. Are you able to run the command successfully at your end?

**Comment by mefellows** [comment]
Yes. 

Can you please try running just `pact-broker`? I want to see if that command executes properly (the binary should be installed from the Pact JS package. If your PATH is not setup to deal, try `./node_modules/.bin/pact-broker`.

If that works, please try `npx @pact-foundation/absolute-version` and let me know in either case if anything unusual happens.

**Comment by mefellows** [comment]
Theory - the `npx @pact-foundation/absolute-version` command is trying to prompt the user to run the command for the first time. We may need to add `--yes` to auto accept.

**Comment by rikumolugds** [comment]
Hi! So, I get `-bash: pact-broker: command not found` when I try `pact-broker`. I don't find pact-broker in ./node_modules/.bin, but I can see it in both ./consumer/node_modules/.bin and ./provider/node_modules/.bin . Might this be the issue? `npx @pact-foundation/absolute-version` gives me `Need to install the following packages:
  @pact-foundation/absolute-version@0.0.4`.

**Comment by mefellows** [comment]
try adding the `--yes` flag to the `npx command` and see if that helps?

_(and yes, apologies, it's in the consumer/provider subfolder)_

**Comment by rikumolugds** [comment]
I used the prompt. `npm WARN deprecated @pact-foundation/absolute-version@0.0.4: Package @pact-foundation/absolute-version has been renamed absolute-version. Please install absolute-version instead
c6706a-step11+c6706a` is what I get. Shall I do `npx absolute-version`?

**Comment by mefellows** [comment]
> I used the prompt.
what does that mean, sorry? 

>  Shall I do npx absolute-version?

No, the code should be updated to use the newer package, but that's not the underlying problem.

**Comment by YOU54F** [comment]
I've removed this for the moment and just used a hard coded variable. 

It would be better to use absolute version from the node_modules folder and install it as a dep.

There are inconsistencies between npx usage in node 14->20 with the use of `--yes` which makes it non portable, and results in the command hanging as its invoked with a bash execute function, so the user doesn't see.

there is a pact:publish2 command, which can be used, will update it properly shortly.

PS, it would be nice if the pact broker cli did this automatically
see https://github.com/pact-foundation/pact_broker-client/issues/100
