### ISSUE TITLE
Step9 npm install failes 

### ISSUE THREAD

**Issue by amitabak-MA** [pact-foundation/pact-workshop-js#87]
Scenario
Checkout the repo
checkout step9 branch 
run npm install 

 ci --prefix provider exited with code 0
npm ERR! code 1
npm ERR! path /Users/amitabak/dev/tutorials/pact-workshop-js
npm ERR! command failed
npm ERR! command sh -c concurrently "npm ci --prefix consumer" "npm ci --prefix provider"

npm ERR! A complete log of this run can be found in: 

Note that step 7 completes OK 
Seems the package-lock.json has some breaking changes in step9

**Comment by mefellows** [comment]
Thanks Amit. Were you up for trying to see if you can fix it? Sounds like maybe a merge issue from Step 8? 

That being said, you shouldn't have to do an `npm ci` in step 9 - what made you try that?

**Comment by amitabak-MA** [comment]
Hi Matt
Decided to jump straight to step9 based on the assumption each lesson already has the previous steps incorporated into its branch 

Ami

**Comment by mefellows** [comment]
It does, so that's a reasonable expectation. would you mind having a try to see if you can correct the lock file? Ideally using npm version 8.9.x

**Comment by YOU54F** [comment]
lock files have all been updated and synchronised so 🤞🏾 shouldn't be an issue now

```
node --version
Now using node v18.17.1 (npm v9.6.7)
```

**Comment by YOU54F** [comment]
Thanks for raising!
