### ISSUE TITLE
Step11 pactBrokerUrl requires one of the following properties

### ISSUE THREAD

**Issue by ghost** [pact-foundation/pact-workshop-js#97]
Have followed all steps up to step11 without issue and getting the following error...

pactBrokerUrl requires one of the following properties: pactUrls,consumerVersionSelectors,consumerVersionTags 

when running the following command  >PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true npm run test:pact --prefix provider

Running the workshop on a MAC with M1 chip

**Comment by PanDymitr** [comment]
Try to add `consumerVersionSelectors` option:

```javascript
consumerVersionSelectors: [{
  latest: true
}],
```

**Comment by YOU54F** [comment]
Thanks @PanDymitr !

That works for our demonstration purposes in the demo, the user will learn about further consumer version selectors in the CI/CD workshop 👍🏾
